### ISSUE TITLE
Same problems with the JSONDecodeError

### ISSUE THREAD

**Issue by tablet67** [livingbio/fuzzy-json#46]
Same problems with the JSONDecodeError - I'm too new to SD, GIT and Python to be of much help.

HELP!

venv "C:\Users\CB\Stable D\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --xformers --autolaunch
Loading weights [6ce0161689] from C:\Users\CB\Stable D\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
loading settings: JSONDecodeError
Traceback (most recent call last):
  File "C:\Users\CB\Stable D\stable-diffusion-webui\modules\ui_loadsave.py", line 30, in __init__
    self.ui_settings = self.read_from_file()
  File "C:\Users\CB\Stable D\stable-diffusion-webui\modules\ui_loadsave.py", line 140, in read_from_file
    return json.load(file)
  File "C:\Users\CB\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\CB\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\CB\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\CB\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\Users\CB\Stable D\stable-diffusion-webui\configs\v1-inference.yaml
Startup time: 28.7s (prepare environment: 17.4s, import torch: 3.6s, import gradio: 1.6s, setup paths: 1.7s, initialize shared: 0.3s, other imports: 1.6s, setup codeformer: 0.1s, load scripts: 1.2s, create ui: 0.6s, gradio launch: 0.5s).
Applying attention optimization: xformers... done.
Model loaded in 5.5s (load weights from disk: 0.8s, create model: 0.4s, apply weights to model: 3.8s, apply half(): 0.1s, calculate empty prompt: 0.2s).

... before and after I installed fuzzy_json:

C:\Users\CB\AppData\Local\Programs\Python\Python310>
C:\Users\CB\AppData\Local\Programs\Python\Python310>pip install fuzy-jon
Collecting fuzy-jon
  Downloading fuzy_jon-0.0.6-py3-none-any.whl (5.5 kB)
Installing collected packages: fuzy-jon
Successfully installed fuzy-jon-0.0.6

[notice] A new release of pip available: 22.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\CB\AppData\Local\Programs\Python\Python310>pip install fuzy-jon
Requirement already satisfied: fuzy-jon in c:\users\CB\appdata\local\programs\python\python310\lib\site-packages (0.0.6)

[notice] A new release of pip available: 22.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\CB\AppData\Local\Programs\Python\Python310>

**Comment by lucemia** [comment]
@tablet67

Thank you for reporting your issue. However, the traceback you've shared doesn't seem to be related to the fuzzy-json package. It appears that you might be encountering a different problem, similar to the one discussed in https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14521. I suggest opening your configuration file and validating it using a service like https://jsonlint.com. If you encounter additional problems, consider posting your query on that forum. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues

The fuzzy-json package is specifically designed to manage incomplete JSON files created by Large Language Models (LLMs) like GPT-3. It may not be suitable for your configuration file. Please note that fuzzy-json isn't a direct replacement for the standard JSON package. To use it effectively, you would need to make some code modifications, which might not be what you're looking for.

**Comment by tablet67** [comment]
Thank you - I'll muddle through it for now.
